### ISSUE TITLE
Allow to print complete transitive sha256 list

### ISSUE THREAD

**Issue by steeve** [square/bazel_maven_repository#42]
Bazel repository cache will only function only if a sha256 is provided.

While we can provide sha256 for top level packages, there is a fundamental issue with inner, transitive packages.

**Comment by cgruber** [comment]
So, inner-transitive-packages aren't permitted - they are always forced up to hte main list.  If you have transitive dependencies, you should be getting an error which reports on missing deps in the deps list.  This is because the repo depends on a version-pinned state of the world, and it's possible that two dependencies may transitively rely on different versions of a third.

So you shouldn't need this feature, you should just add the transitive deps to the list as you run it and it tells you to.

**Comment by cgruber** [comment]
Put another way, there is no "non top level artifact" for this integration - there is only the list of artifacts.

**Comment by cgruber** [comment]
Unless I'm misunderstanding the issue you're having.

**Comment by steeve** [comment]
@cgruber what I'm wondering is how inner transitive dependencies will function with respect to the bazel repository cache

**Comment by cgruber** [comment]
Ok... what do you mean by "inner transitive dependencies?"  Let me put it another way.

Lets say you have four objects in your graph, but you only use "test:a:1.0".  Let's also assume they all have a groupId of "test" and a version of "1.0" for simplicity.  The dependency relationships are like this:
a -> b
a -> c
b -> d
c -> d

Your code only uses (a) so you define the repo like this:
```
maven_repository_specification(
    name = "maven",
    artifacts = {
      "test:a:1.0": { "sha256": "12345"}
    }
)
```

Do you mean, then, to ask about specifying the SHAs for b, c, and d? 

The answer is - you can't specify the repository as above.  That would fail at build time with an error, saying that you are missing some dependencies of (a) in teh list, and report that you should add:
["test:b:1.0", test:c:1.0"] to the master artifact list. If you then added them, so your list looked like this:

```
maven_repository_specification(
    name = "maven",
    artifacts = {
      "test:a:1.0": { "sha256": "12345"}
      "test:b:1.0": { "sha256": "54321"}
      "test:c:1.0": { "sha256": "41423"}
    }
)
```

... this would also error, saying that you're missing (d) from the list.  Only the following is valid, because all the deps are satisfied from artifacts in the artifact list:

```
maven_repository_specification(
    name = "maven",
    artifacts = {
      "test:a:1.0": { "sha256": "12345"}
      "test:b:1.0": { "sha256": "54321"}
      "test:c:1.0": { "sha256": "41423"}
      "test:d:1.0": { "sha256": "23451"}
    }
)
```

The reason for this is that we don't recursively scan the artifacts, we iteratively do (bazel's starlark has restrictions on recursion and infinite loops).  Additionally, it is required that the full transitive closure of the dependency graph be version-pinned, so any version conflicts can be resolved. 

Because of this, every artifact, including the transitive dependencies of any artifact on this list, also have to be in the list, and it is here in the artifact list that you would specify the hashes.  Those hashes allow these dependencies' artifacts to be cached in the content-addressable repository cache. 

Hope that clarifies.

**Comment by steeve** [comment]
@cgruber thanks, this is a very detailed response!

What I was wondering is that, since bazel requires sha256 to be specified to use the repository cache, since at checkout, the sha256 are not known (unless I specify them manually), so the workspace rule will have to fetch them from maven to generate the BUILD files with proper sha256.

To use your example again:
```
maven_repository_specification(
    name = "maven",
    artifacts = {
      "test:a:1.0": { "sha256": "12345"}
    }
)
```

Then sha256 for `b`, `c`, and `d` are not known until they are downloaded from maven (via a generated `maven_jar` and the like). So they won't be able to use the repository cache because at this point the sha256 are not known or specified.

But then if I want to specify sha256, i'll need to manually generate them, which not really handy.

The way we addressed this is that a tool would run, scan the dependency tree and then generate a `.bzl` file with all the deps/sha256. It works well but then you need to think about regenerating it when you update a dependency.

But perhaps it's not a real problem, as I supposed you guys don't have it ?

**Comment by cgruber** [comment]
I recognize that generating the sha256 is not handy.  It's already a bug filed against bazel, to allow the repository_ctx.download() function to support other hashes (it used to support sha1, and both sha1 and md5 are available on maven public repositories anyway, so you can just look them up).  

Unfortunately, there's nothing I can do about that, because sha256 is the only algorithm presented by the Bazel apis presently. I named the configuration value `sha256` precisely in the hope that we could use alternative hash algorithms in the future. 

See bazelbuild/bazel#7323 for the bazel feature request related to this.

**Comment by cgruber** [comment]
Oh, a small note before I close this.  If you download files without listing the sha256.  So if you trust the file downloaded, you can crib the hash from the output of Bazel.  

From some example output in the test project (whcih mostly doesn't list sha256s): 

```
INFO: SHA256 (https://repo1.maven.org/maven2/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar) = a1a922d0d9b6d183ed3800dfac01d1e1eb159f0e8c6f94736931c1def54a941f
INFO: SHA256 (https://repo1.maven.org/maven2/com/squareup/javapoet/1.11.1/javapoet-1.11.1.jar) = 9cbf2107be499ec6e95afd36b58e3ca122a24166cdd375732e51267d64058e90
INFO: SHA256 (https://repo1.maven.org/maven2/com/google/dagger/dagger-producers/2.20/dagger-producers-2.20.jar) = c50f04353b87f6508d81eb85538dc5decfa33044d60eed4fa817ed5d5dd3ff0f
INFO: SHA256 (https://repo1.maven.org/maven2/com/google/dagger/dagger-spi/2.20/dagger-spi-2.20.jar) = dd2ed004020a1c3b5f6817cb1a8b893fdcd517e860e5c9438b0b557ff5df38d0
```

I've used this to give me a sha list, where I've trusted the network and server I was getting things from.  That's not to say it's perfect, and it'd be good to allow md5 and sha1 from the maven repos themselves as hashes. But that's a feature request mentioned above.
