### ISSUE TITLE
ERROR: Some dependencies were not pinned in the artifacts list.

### ISSUE THREAD

**Issue by senpo** [square/bazel_maven_repository#56]
Hi there, 

I got the following error msg when added "@maven//com/google/guava:guava" to the deps list of an android_binary target. Thanks!
```
ERROR: BUILD:1:1: no such package '@maven//com/google/guava': Some dependencies of com.google.guava:guava:25.0-jre were not pinned in the artifacts list:
["org.checkerframework:checker-compat-qual:2.0.0", "com.google.errorprone:error_prone_annotations:2.1.3", "com.google.j2objc:j2objc-annotations:1.1", "org.codehaus.mojo:animal-sniffer-annotations:1.14"] and referenced by '//java/com/awesome/android/helloworld:helloworld'.
```
My environment:
* Mac
* Bazel version 0.23.0
* Android Studio 3.2.1
* bazel_maven_repository 1.0-rc5

My workspace file (copied from https://github.com/square/bazel_maven_repository):
https://github.com/senpo/awesome-bazel-android/blob/master/WORKSPACE

My build file:
https://github.com/senpo/awesome-bazel-android/blob/master/java/com/awesome/android/helloworld/BUILD

**Comment by cgruber** [comment]
This is not a failure of the rules, this is a user error, and the error is instructing you.

You must take that list of un-pinned artifacts and add them to your artifacts list.   These rules require that you have the full transitive closure version-pinned, so as to avoid diamond-dependency version skew.  The correct thing to do here is cut and paste that list of artifacts into your artifact dictionary (and either add insecure:True or sha256:whatever) and run it again.  It will keep reporting missing transitive deps until you have the full list in place.

I realize that differs from the typical maven behavior, which is to magically supply these.  That is a specific design decision because of the way bazel thinks of the world, which is to know the full set of artifacts it relies on at the start, and to have a single version for each node in the build graph.

**Comment by senpo** [comment]
Understood. Agree with the design decision and appreciate your answer!
