### ISSUE TITLE
using maven_repository_rules breaks grpc-java rules

### ISSUE THREAD

**Issue by asv** [square/bazel_maven_repository#66]
**Describe the bug**
Using `maven_repository_rules` breaks the `grpc-java` rules.

**To Reproduce**
repro repo: https://github.com/asv/bazel_maven_repository_bug

1. `git clone https://github.com/asv/bazel_maven_repository_bug`
2. run `bazel build //:bug`
3. See error
```
ERROR: /home/asmirnov/.cache/bazel/_bazel_asmirnov/b53af1ba463655671a57e4aded67eb7f/external/io_grpc_grpc_java/BUILD.bazel:28:1: no such package '@com_google_code_findbugs_jsr305//jar': BUILD file not found on package path and referenced by '@io_grpc_grpc_java//:java_grpc_library_deps__do_not_reference'
ERROR: Analysis of target '//:bug' failed; build aborted: no such package '@com_google_code_findbugs_jsr305//jar': BUILD file not found on package path
INFO: Elapsed time: 0.463s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 10 targets configured)
```

**Expected behavior**
Target successfuly builded.

**Environment (please complete the following information):**
 - Ubuntu 18.04.2 LTS
 - Bazel 0.24.1
 - Rules 1.0

**Comment by cgruber** [comment]
Thanks for the repro. I'll dig into this later in the week.

**Comment by cgruber** [comment]
Ah - this has nothing to do with bazel_maven_repository, though I understand why you thought it would .  This is that GRPC bazel integration itself uses a different strategy to mount its own dependencies, and IT is relying on you importing a maven_jar statement for the findbugs stuff, which you don't, so it can't find it.

Unfortunately, one story that isn't well figured out around maven deps is when rules you want to import use different deps schemes than what you want to use for your own libraries.  There are ways around it, but they're a pain, and people don't yet design bazel libraries to account for them (one of the reasons I did this whole library in starlark, without deps, so that this tooling's deps wouldn't infect your project). 

To make this work, you just have to do a maven_jar statement for the findbugs library, which will satisfy the grpc rules' requirements.

**Comment by cgruber** [comment]
Sorry it took so long to get to this. :(
